---
- name: sysyconfig/i18nを日本語に設定
  raw: sed -i.org -e "s/LANG=\"C\"/LANG=\"ja_JP.UTF-8\"/" /etc/sysconfig/i18n
- name: 不必要なサービスを停止
  service: name={{ item }} state=stopped enabled=no
  ignore_errors: yes
  with_items:
    - lvm2-monitor
    - netfs
- name: networkをリスタート
  action: service name=network state=restarted
- name: Gitをインストール
  yum: pkg={{ item }} state=installed
  with_items:
    - git
    - git-svn