---
- name: PHPをインストール
  action: yum pkg={{ item }} state=installed
  with_items:
    - php
    - php-pear
    - php-devel
    - php-xml
    - php-mbstring
    - php-mysql
    - php-gd
  notify:
    - restart httpd
- name: config PHP
  action: ini_file dest=/etc/php.d/my.ini section=global option=memory_limit value=256M mode=0600
  notify:
    - restart httpd
- name: config PHP
  action: ini_file dest=/etc/php.d/my.ini section=global option=short_open_tag value=Off mode=0600
  notify:
    - restart httpd
- name: config PHP
  action: ini_file dest=/etc/php.d/my.ini section=global option=max_execution_time value=0 mode=0600
  notify:
    - restart httpd
- name: config PHP
  action: ini_file dest=/etc/php.d/my.ini section=global option=post_max_size value='512M' mode=0600
  notify:
    - restart httpd
- name: config PHP
  action: ini_file dest=/etc/php.d/my.ini section=global option=upload_max_filesize value='512M' mode=0600
  notify:
    - restart httpd
- name: config PHP
  action: ini_file dest=/etc/php.d/my.ini section=mbstring option=mbstring.language value=Japanese mode=0600
  notify:
    - restart httpd
- name: config PHP
  action: ini_file dest=/etc/php.d/my.ini section=mbstring option=mbstring.internal_encoding value=utf-8 mode=0600
  notify:
    - restart httpd
- name: config timezone
  action: ini_file dest=/etc/php.d/timezone.ini section=Date option=date.timezone value=Asia/Tokyo mode=0600
  notify:
    - restart httpd